
 -1 VALUE 'LIT
 -1 VALUE 'IMGLIT
 -1 VALUE 'DATADR
 -1 VALUE 'GET

\ -1 VALUE '(<'>)
\ -1 VALUE 'BRANCH
\ -1 VALUE '?BRANCH
\ -1 VALUE 'EXIT
-1 VALUE '&DBG
-1 VALUE 'NEST
\ -1 VALUE 'UNNEST
\ -1 VALUE 'THCOD
\ -1 VALUE ';EXIT
-1 VALUE '+
-1 VALUE 'NOOP
-1 VALUE '(S")
-1 VALUE '(Z")
-1 VALUE 'DUP
-1 VALUE 'DROP
-1 VALUE 'OVER
-1 VALUE '=
-1 VALUE 'ICREATE
-1 VALUE 'TYPE

-1 VALUE 'DEBEXEC
-1 VALUE 'DEB#ADBG
-1 VALUE 'GODEB
-1 VALUE 'GO
-1 VALUE 'MONITOR
-1 VALUE 'R>
-1 VALUE '>R
-1 VALUE VBREAK
-1 VALUE 'P_M>F

-1 VALUE 'QBRANCH

-1 VALUE '(LEAVE)
-1 VALUE 'XDO
-1 VALUE '(DO)
-1 VALUE '(?DO)
-1 VALUE 'ADD[ESP],TOS

\ -1 VALUE 'TOTC
-1 VALUE 'PERFORM
-1 VALUE 'EXECUTE
-1 VALUE 'CATCH
-1 VALUE 'THROW 

0 VALUE 'DOCREATE
0 VALUE 'DOCONSTANT
0 VALUE 'DOVALUE
0 VALUE 'DOVECT
0 VALUE 'DOFIELD


0x51A0C0 VALUE 'Beep
0 VALUE 'CloseHandle
0x51A0D0 VALUE 'CreateFileA
0x51A0D8 VALUE 'CreateThread
0x51A0E0 VALUE 'ExitProcess
0x51A0E8 VALUE 'GetCommandLineA
0x51A0F0 VALUE 'GetProcAddress
0 VALUE 'GetStdHandle
0x51A100 VALUE 'LoadLibraryA
0x519108 VALUE 'ReadConsoleInputA
0x51A110 VALUE 'ReadFile
0x51A118 VALUE 'SetFilePointer
0x51A120 VALUE 'Sleep
0x51A128 VALUE 'VirtualAlloc
0x51A130 VALUE 'VirtualFree
0x519138 VALUE 'WriteFile

0 VALUE _NXCALL0
0 VALUE _NXCALL1
0 VALUE _NXCALL2
0 VALUE _NXCALL3
0 VALUE _NXCALL4
0 VALUE _NXCALL5


